title: Nighthawk-Pages
description: "October 2023 to November 2023"
owner_name: Chrissie Zhou
github_username: Chrissiez
github_repo: "DinoGame-Pages"
baseurl: "/DinoGame-Pages"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Chrissiez/DinoGame-Pages"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
